# Generated by Django 4.2.4 on 2023-08-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=265, verbose_name='Полное имя')),
                ('phone_number', models.CharField(max_length=265, verbose_name='Номер телефона')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Пол')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='doctors.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приемы',
                'ordering': ('-id',),
            },
        ),
    ]
