# Generated by Django 4.2.4 on 2023-08-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('appointment', '0003_remove_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.appointment', verbose_name='Прием')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Время для приемов',
                'ordering': ('-id',),
            },
        ),
    ]
