# Generated by Django 4.2.4 on 2023-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointmenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
