# Generated by Django 4.2.4 on 2023-08-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointmenttime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointment.appointment', verbose_name='Прием'),
        ),
    ]
