# Generated by Django 4.2.4 on 2023-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointmenttime_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='isAvailable',
            field=models.BooleanField(default=False, verbose_name='Зянато'),
        ),
    ]
