# Generated by Django 4.2.4 on 2023-08-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('appointment', '0007_appointmenttime_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to='doctors.doctor', verbose_name='Доктор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_tim', to='appointment.appointmenttime', verbose_name='Время'),
        ),
    ]
