# Generated by Django 4.2.4 on 2023-08-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('appointment', '0009_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment_time', to='doctors.doctor', verbose_name='Доктор'),
        ),
    ]
