# Generated by Django 4.2.4 on 2023-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=265, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото для галлереи',
                'verbose_name_plural': 'Фотографии для галлереи',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265, verbose_name='Название')),
                ('image', models.ImageField(upload_to='license/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ('-id',),
            },
        ),
    ]
