# Generated by Django 4.2.4 on 2023-08-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='Фото')),
                ('full_name', models.CharField(max_length=265, verbose_name='Полное имя')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('job', models.CharField(blank=True, max_length=265, null=True, verbose_name='Работа')),
                ('phone_number', models.CharField(blank=True, max_length=265, null=True, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HospitalAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265, verbose_name='Название')),
                ('image', models.ImageField(upload_to='hospital_awards_imeges/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Награда больницы',
                'verbose_name_plural': 'Награды больницы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DoctorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor_awards/', verbose_name='Фото')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_awards', to='doctors.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ('-id',),
            },
        ),
    ]
